### ISSUE TITLE
Some old digsites not known

### ISSUE THREAD

**Issue by SirJorb** [javierhimura/ArchyBFA#2]
Encountered some digsites in Eastern Kingdoms that the addon doesn't quite understand. For example, the Felstone Fossil Field digsite in Western Plaguelands is listed as an 'unknown' race, as well as being supposedly located in Tirisfal Glades. Likewise, the Thandol Span digsite in the Wetlands is listed as unknown, and also is incorrectly listed as being in Twilight Highlands.

![image](https://user-images.githubusercontent.com/23423782/236537122-b6ab2a1e-a711-4514-b448-583e07d69f64.png)

**Comment by SirJorb** [comment]
Got this error when looting fragments at Thandol Span, as well. Notably this error does not occur at digsites it recognizes, only the 'unknown' ones.

`1x Archy/Archy.lua:1580: attempt to index field '?' (a nil value)`
`[string "@Archy/Archy.lua"]:1580: in function '?'`
`[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>`
`[string "=[C]"]: ?`
`[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>`
`[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function 'Fire'`
`[string "@DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>`

`Locals:`
`self = <table> {`
` UpdatePlayerPosition = <function> defined @Archy/Archy.lua:1235`
` SetDefaultModuleLibraries = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:363`
` SetSinkStorage = <function> defined @Archy/Libs/LibSink-2.0/LibSink-2.0/LibSink-2.0.lua:829`
` EnableModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:328`
` modules = <table> {`
` }`
` CancelTimer = <function> defined @DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:147`
` IterateEmbeds = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:438`
` SecureHookScript = <function> defined @Archy/Libs/AceHook-3.0/AceHook-3.0.lua:409`
` SocketClicked = <function> defined @Archy/Archy.lua:480`
` RawHookScript = <function> defined @Archy/Libs/AceHook-3.0/AceHook-3.0.lua:394`
` optionsFrame = ArchyAboutPanel {`
` }`
` version = "10.0.2.0"`
` Printf = <function> defined @DataStore/libs/AceConsole-3.0/AceConsole-3.0.lua:65`
` baseName = "Archy"`
` SetDefaultModulePrototype = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:405`
` GetSinkAce3OptionsDataTable = <function> defined @Archy/Libs/LibSink-2.0/LibSink-2.0/LibSink-2.0.lua:672`
` SetupOptions = <function> defined @Archy/Config.lua:1681`
` LDBTooltipShow = <function> defined @Archy/Tooltip.lua:272`
` defaultModuleState = true`
` SpawnToast = <function> defined @Archy/Libs/LibToast-1.0/LibToast-1.0.lua:538`
` IsEnabled = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:447`
` SKILL_LINES_CHANGED = <function> defined @Archy/Archy.lua:1812`
` ScheduleTimer = <function> defined @DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:94`
` DisableModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:346`
` SaveFramePosition = <function> defined @Archy/Interface.lua:1030`
` SetFramePosition = <function> defined @Archy/Interface.lua:998`
` UpdateTracking = <function> defined @Archy/Archy.lua:1323`
` SetDefaultModuleState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:383`
` RegisterMessage = <function> defined @AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:80`
` UnregisterMessage = <function> defined @AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:143`
` RegisterBucketEvent = <function> defined @Archy/Libs/AceBucket-3.0/AceBucket-3.0.lua:180`
` UNIT_SPELLCAST_SENT = <function> defined @Archy/Archy.lua:1827`
` hooks = <table> {`
` }`
` ResizeGraphicalDigSiteDisplay = <function> defined @Archy/Interface.lua:886`
` BAG_UPDATE_DELAYED = <function> defined @Archy/Archy.lua:1478`
` LoadWorldData = <function> defined @Archy/Archy.lua:802`
` db = <table> {`
` }`
` SearchDigsiteTemplate = <function> defined @Archy/Archy.lua:599`
` RegisterChatCommand = <function> defined @DataStore/libs/AceConsole-3.0/AceConsole-3.0.lua:81`
` DisableProgressBar = <function> defined @Archy/Interface.lua:66`
` SetEnabledState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:420`
` Hook = <function> defined @Archy/Libs/AceHook-3.0/AceHook-3.0.lua:273`
` enabledState = true`
` COMBAT_LOG_EVENT_UNFILTERED = <function> defined @Archy/Archy.lua:1540`
` RegisterEvent = <function> defined @AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:80`
` UNIT_SPELLCAST_SUCCEEDED = <function> defined @Archy/Archy.lua:1838`
` TAXIMAP_OPENED = <function> defined @Archy/Archy.lua:1823`
` TAXIMAP_CLOSED = <function> defined @Archy/Archy.lua:1819`
` PLAYER_CONTROL_GAINED = <function> defined @Archy/Archy.lua:1677`
` Iter`

**Comment by SirJorb** [comment]
I also got a message saying '25 missing digsites found. Please run /archy debug and report the list'. However, the list was just this:

`[12:07:44] `
`		[215] = {`
`			id = 215, -- Terror Wing Fossil Field`
`			mapID = 36, -- Burning Steppes`
`			raceID = RaceID.Unknown,`
`		},`

**Comment by javierhimura** [comment]
Sorry for the delay.

I have fixed the code so it doesn't fail when exploring an unknown dig site. With the new release, /archy debug command should report all the missing dig sites that you have been able to collect while using the addon.

Keep in mind there is no way to know which race belongs to a dig site not available on the addon database until you collect a fragment there. Also, the addon can't say the correct zone of an unknown dig site because it is available on Blizzard UI in the right zone map and other zone maps of the same continent.

The original author collected a massive database of dig sites. Still, unfortunately, Blizzard changed the coordinates of many sites and the id that identifies the site when they revamped the map UI in Legion.
