### ISSUE TITLE
10.1.5 bug

### ISSUE THREAD

**Issue by Addonman** [javierhimura/ArchyBFA#3]
Count: 1
Message: Interface/AddOns/Archy/Race.lua line 77:
   attempt to call field 'RequestArtifactCompletionHistory' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "=(tail call)"]: ?
   [string "=(tail call)"]: ?
   [string "@Interface/AddOns/Archy/Race.lua"]:77: InitializeRaces()
   [string "@Interface/AddOns/Archy/Archy.lua"]:915:
      Interface/AddOns/Archy/Archy.lua:854
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66:
      ...AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:61
   [string "@Interface/AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: EnableAddon()
   [string "@Interface/AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:626:
      ...AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:611
   [string "=[C]"]: LoadAddOn()
   [string "@Interface/FrameXML/UIParent.lua"]:544: UIParentLoadAddOn()
   [string "@Interface/FrameXML/UIParent.lua"]:753: MajorFactions_LoadUI()
   [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:175: SetUpMajorFactionList()
   [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:168: RefreshMajorFactionList()
   [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:163: RefreshOverlay()
   [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:154:
      ...sionLandingPage/Blizzard_DragonflightLandingPage.lua:150
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: CreateFrame()
   [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:118: CreateOverlay()
   [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: RefreshExpansionOverlay()
   [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35:
      ...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33
Locals:
(*temporary) = <function> defined =[C]:-1

**Comment by Addonman** [comment]
Message: Interface/AddOns/Archy/Archy.lua line 1098:
   attempt to index field 'ARTIFACTS_RESTORE' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Archy/Archy.lua"]:1098:
      Interface/AddOns/Archy/Archy.lua:1082
   [string "@Interface/AddOns/Archy/Archy.lua"]:1115: ScanBags()
   [string "@Interface/AddOns/Archy/Archy.lua"]:1479: ?()
   [string "@Interface/AddOns/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109:
      ...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:109
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19:
      ...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15
   [string "@Interface/AddOns/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: Fire()
   [string "@Interface/AddOns/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120:
      Interface/AddOns/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119
Locals:
(*temporary) = <function> defined =[C]:-1

**Comment by javierhimura** [comment]
Updated the addon to work with 10.1.5
